#Course Completion Predictor

###Day 1-Setup and Initial Exploration

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
train_path = "/content/drive/MyDrive/course-completion-predictor/data/cohort_train.csv"
holdout_path = "/content/drive/MyDrive/course-completion-predictor/data/cohort_holdout.csv"

train_df = pd.read_csv(train_path)
holdout_df = pd.read_csv(holdout_path)

print("Datasets loaded successfully.")

Datasets loaded successfully.

In [ ]:
print("Training data shape:")
print(train_df.shape)

print("Holdout data shape:")
print(holdout_df.shape)

Training data shape:
(2484, 19)
Holdout data shape:
(400, 18)

In [ ]:
train_df.head()

,learner_id,signup_date,age,city_tier,education,hours_per_week_pledged,weekly_logins_avg,assignments_submitted,forum_posts,video_watch_pct,has_mentor,device,referral_source,payment_plan,days_since_last_login,certificate_issued,final_score,notes,completed_course
0,L-01146,2026-01-22,24.0,Tier 3,OTHER,8.3,4.20,3,6,89.0,Y,MOBILE,instagram,scholarship,1,Y,78.6,NaN,1.0
1,L-00695,2026-06-02,15.0,Tier 1,Bachelors,1.0,2.54,0,4,31.2,no,desktop,instagram,paid,33,no,NaN,NaN,0.0
2,L-00530,20-05-2026,24.0,tier-2,Diploma,10.3,0.50,0,3,10.7,NaN,laptop,instagram,scholarship,23,No,NaN,follow up next intake,0.0
3,L-02228,2026-01-19,23.0,1,B.Tech,1.6,3.01,0,0,40.2,no,mobile,school_partner,free,33,FALSE,NaN,duplicate? check,0.0
4,L-00914,16/02/2026,21.0,2,High School,9.8,4.36,3,1,36.7,no,Desktop,instagram,paid,19,TRUE,67.1,follow up next intake,1.0

In [ ]:
print(train_df.columns)

Index(['learner_id', 'signup_date', 'age', 'city_tier', 'education',
       'hours_per_week_pledged', 'weekly_logins_avg', 'assignments_submitted',
       'forum_posts', 'video_watch_pct', 'has_mentor', 'device',
       'referral_source', 'payment_plan', 'days_since_last_login',
       'certificate_issued', 'final_score', 'notes', 'completed_course'],
      dtype='object')

In [ ]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2484 entries, 0 to 2483
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   learner_id              2484 non-null   object
 1   signup_date             2484 non-null   object
 2   age                     2332 non-null   float64
 3   city_tier               2431 non-null   object
 4   education               2394 non-null   object
 5   hours_per_week_pledged  2376 non-null   float64
 6   weekly_logins_avg       2388 non-null   float64
 7   assignments_submitted   2484 non-null   int64
 8   forum_posts             2484 non-null   int64
 9   video_watch_pct         2337 non-null   float64
 10  has_mentor              2420 non-null   object
 11  device                  2484 non-null   object
 12  referral_source         2484 non-null   object
 13  payment_plan            2484 non-null   object
 14  days_since_last_login   2484 non-null   int64
 15  certificate_issued      2484 non-null   object
 16  final_score             1162 non-null   float64
 17  notes                   1240 non-null   object
 18  completed_course        2475 non-null   float64
dtypes: float64(6), int64(3), object(10)
memory usage: 368.8+ KB

In [ ]:
train_df.isnull().sum()

learner_id                   0
signup_date                  0
age                        152
city_tier                   53
education                   90
hours_per_week_pledged     108
weekly_logins_avg           96
assignments_submitted        0
forum_posts                  0
video_watch_pct            147
has_mentor                  64
device                       0
referral_source              0
payment_plan                 0
days_since_last_login        0
certificate_issued           0
final_score               1322
notes                     1244
completed_course             9
dtype: int64

In [ ]:
print("Number of duplicate rows:", train_df.duplicated().sum())

Number of duplicate rows: 83

In [ ]:
print(train_df["completed_course"].value_counts())

completed_course
0.0    1561
1.0     914
Name: count, dtype: int64

In [ ]:
print(train_df["completed_course"].value_counts(normalize=True) * 100)

completed_course
0.0    63.070707
1.0    36.929293
Name: proportion, dtype: float64

Day 2-Data Exploration

In [ ]:
print(train_df["city_tier"].value_counts(dropna=False))

city_tier
2         793
1         663
3         498
T2         71
Tier 2     68
tier-2     65
Tier 1     57
tier-1     57
NaN        53
T1         46
tier-3     40
Tier 3     38
T3         35
Name: count, dtype: int64

In [ ]:
print(train_df["education"].value_counts(dropna=False))

education
Bachelors          629
High School        587
Diploma            396
Masters            173
Other              107
NaN                 90
B.Tech              52
highschool          50
DIPLOMA             50
HS                  44
Bachelor's          40
bachelors           40
diploma             38
bachelor degree     38
high school         35
High-School         34
Master's            17
M.Sc                17
other               15
unknown             12
OTHER               10
masters             10
Name: count, dtype: int64

In [ ]:
print(train_df["has_mentor"].value_counts(dropna=False))

has_mentor
0        310
No       299
FALSE    295
no       293
N        290
1        199
TRUE     191
Yes      187
Y        184
yes      172
NaN       64
Name: count, dtype: int64

In [ ]:
print(train_df["device"].value_counts(dropna=False))

device
mobile      1017
laptop       599
desktop      232
tablet       119
Mobile       101
phone         88
MOBILE        86
notebook      74
Laptop        68
Desktop       35
Tablet        27
PC            27
ipad          11
Name: count, dtype: int64

In [ ]:
print(train_df["referral_source"].value_counts(dropna=False))

referral_source
instagram         687
school_partner    554
friend            475
youtube           367
ngo_outreach      265
other             136
Name: count, dtype: int64

In [ ]:
print(train_df["payment_plan"].value_counts(dropna=False))

payment_plan
free           1130
scholarship     811
paid            543
Name: count, dtype: int64

In [ ]:
train_df[[
    "age",
    "hours_per_week_pledged",
    "weekly_logins_avg",
    "assignments_submitted",
    "forum_posts",
    "video_watch_pct",
    "days_since_last_login"
]].describe()

,age,hours_per_week_pledged,weekly_logins_avg,assignments_submitted,forum_posts,video_watch_pct,days_since_last_login
count,2332.000000,2376.000000,2388.000000,2484.000000,2484.000000,2337.000000,2484.000000
mean,22.714408,8.437626,3.075096,3.655797,3.247585,46.617758,19.288647
std,20.278475,18.435356,1.502140,2.493706,2.505309,25.264902,11.864180
min,-3.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,18.000000,4.800000,2.070000,2.000000,1.000000,28.400000,10.000000
50%,21.000000,7.100000,3.125000,4.000000,3.000000,45.400000,18.000000
75%,24.000000,9.500000,4.082500,5.000000,5.000000,63.900000,27.000000
max,300.000000,326.800000,7.000000,10.000000,14.000000,115.300000,70.000000

In [ ]:
print("Duplicate learner IDs:", train_df["learner_id"].duplicated().sum())

Duplicate learner IDs: 84

In [ ]:
duplicate_ids = train_df[train_df["learner_id"].duplicated(keep=False)]

print(duplicate_ids[["learner_id"]].sort_values("learner_id").head(30))

     learner_id
1417    L-00002
1245    L-00002
856     L-00056
1570    L-00056
2481    L-00082
651     L-00082
263     L-00141
156     L-00141
167     L-00229
172     L-00229
1082    L-00268
687     L-00268
1840    L-00406
59      L-00406
2196    L-00414
1948    L-00414
911     L-00453
1694    L-00453
361     L-00454
2356    L-00454
459     L-00480
1816    L-00480
2398    L-00489
2303    L-00489
575     L-00495
1605    L-00495
1169    L-00501
2005    L-00501
2283    L-00514
2371    L-00514

In [ ]:
duplicate_ids = train_df[train_df["learner_id"].duplicated(keep=False)]

print(duplicate_ids.sort_values("learner_id").head(10).to_string())

     learner_id signup_date   age city_tier  education  hours_per_week_pledged  weekly_logins_avg  assignments_submitted  forum_posts  video_watch_pct has_mentor   device referral_source payment_plan  days_since_last_login certificate_issued  final_score                    notes  completed_course
1417    L-00002  2026-05-20  22.0         2    Diploma                     8.6               3.18                      2            3              8.8      FALSE   Mobile          friend         paid                     13                  0          NaN                      NaN               0.0
1245    L-00002  2026-05-20  22.0         2    Diploma                     8.6               3.18                      2            3              8.8      FALSE   Mobile          friend         paid                     13                  0          NaN                      NaN               0.0
856     L-00056  2026-05-13  22.0         1      Other                     9.7               0.50                      3            1             10.8       TRUE   laptop  school_partner  scholarship                     20                 No          NaN                      NaN               0.0
1570    L-00056  2026-05-13  22.0         1      Other                     9.7               0.50                      3            1             10.8       TRUE   laptop  school_partner  scholarship                     20                 No          NaN                      NaN               0.0
2481    L-00082  2026-01-16  28.0         2  Bachelors                     8.6               2.13                      5            5             40.8        yes  desktop       instagram  scholarship                     25                Yes         83.0        duplicate?  check               1.0
651     L-00082  2026-01-16  28.0         2  Bachelors                     8.6               2.13                      5            5             40.8        yes  desktop       instagram  scholarship                     25                Yes         83.0        duplicate?  check               1.0
263     L-00141  2026-06-23  25.0         2  Bachelors                     3.3               3.22                      1            1             14.7      FALSE   MOBILE       instagram         paid                     25                 no         88.6  asked about certificate               1.0
156     L-00141  2026-06-23  25.0         2  Bachelors                     3.3               3.22                      1            1             14.7      FALSE   MOBILE       instagram         paid                     25                 no         88.6  asked about certificate               1.0
167     L-00229  23-03-2026  15.0         1        NaN                     9.9               5.29                      7            3             37.6          N   laptop       instagram         free                      2                yes         67.3    follow up next intake               1.0
172     L-00229  23-03-2026  15.0         1        NaN                     9.9               5.29                      7            3             37.6          N   laptop       instagram         free                      2                yes         67.3    follow up next intake               1.0

In [ ]:
missing_target = train_df[train_df["completed_course"].isna()]

print(missing_target[["learner_id", "completed_course"]].to_string(index=False))

learner_id  completed_course
   L-02093               NaN
   L-02232               NaN
   L-01467               NaN
   L-00516               NaN
   L-02515               NaN
   L-02467               NaN
   L-00668               NaN
   L-01726               NaN
   L-02538               NaN

Day 3-Data Cleaning

In [ ]:
clean_df = train_df.copy()

print("Cleaning copy created.")
print(clean_df.shape)

Cleaning copy created.
(2484, 19)

In [ ]:
clean_df = clean_df.drop_duplicates()

print("Shape after removing duplicate rows:")
print(clean_df.shape)

Shape after removing duplicate rows:
(2401, 19)

In [ ]:
print("Number of duplicate rows now:", clean_df.duplicated().sum())

Number of duplicate rows now: 0

In [ ]:
print("Shape after removing duplicate rows:")
print(clean_df.shape)

print("Number of duplicate rows now:", clean_df.duplicated().sum())

Shape after removing duplicate rows:
(2401, 19)
Number of duplicate rows now: 0

In [ ]:
print(clean_df["city_tier"].value_counts(dropna=False))

city_tier
2         769
1         647
3         474
T2         71
Tier 2     65
tier-2     64
Tier 1     55
tier-1     54
NaN        49
T1         45
tier-3     39
Tier 3     35
T3         34
Name: count, dtype: int64

In [ ]:
city_tier_mapping = {
    "T1": 1,
    "Tier 1": 1,
    "tier-1": 1,
    "T2": 2,
    "Tier 2": 2,
    "tier-2": 2,
    "T3": 3,
    "Tier 3": 3,
    "tier-3": 3
}

clean_df["city_tier"] = clean_df["city_tier"].replace(city_tier_mapping)

In [ ]:
print(clean_df["city_tier"].value_counts(dropna=False))

city_tier
2      769
1      647
3      474
2      200
1      154
3      108
NaN     49
Name: count, dtype: int64

In [ ]:
print(clean_df["city_tier"].apply(type).value_counts())

city_tier
<class 'str'>      1890
<class 'int'>       462
<class 'float'>      49
Name: count, dtype: int64

In [ ]:
clean_df["city_tier"] = clean_df["city_tier"].astype("string").str.strip()

In [ ]:
city_tier_mapping = {
    "T1": 1,
    "Tier 1": 1,
    "tier-1": 1,
    "T2": 2,
    "Tier 2": 2,
    "tier-2": 2,
    "T3": 3,
    "Tier 3": 3,
    "tier-3": 3
}

clean_df["city_tier"] = clean_df["city_tier"].replace(city_tier_mapping)

In [ ]:
print(clean_df["city_tier"].value_counts(dropna=False))

city_tier
2       969
1       801
3       582
<NA>     49
Name: count, dtype: Int64

In [ ]:
print(clean_df["education"].value_counts(dropna=False))

education
Bachelors          607
High School        569
Diploma            380
Masters            168
Other              104
NaN                 87
DIPLOMA             50
B.Tech              50
highschool          48
HS                  43
bachelors           39
Bachelor's          38
diploma             38
bachelor degree     37
High-School         34
high school         34
Master's            16
M.Sc                16
other               13
OTHER               10
masters             10
unknown             10
Name: count, dtype: int64

In [ ]:
clean_df["education"] = clean_df["education"].astype("string").str.strip()

In [ ]:
education_mapping = {
    "Bachelors": "Bachelor",
    "bachelors": "Bachelor",
    "Bachelor's": "Bachelor",
    "bachelor degree": "Bachelor",
    "B.Tech": "Bachelor",

    "High School": "High School",
    "highschool": "High School",
    "high school": "High School",
    "HS": "High School",
    "High-School": "High School",

    "Diploma": "Diploma",
    "DIPLOMA": "Diploma",
    "diploma": "Diploma",

    "Masters": "Masters",
    "masters": "Masters",
    "Master's": "Masters",
    "M.Sc": "Masters",

    "Other": "Other",
    "other": "Other",
    "OTHER": "Other",
    "unknown": "Other"
}

clean_df["education"] = clean_df["education"].replace(education_mapping)

In [ ]:
print(clean_df["education"].value_counts(dropna=False))

education
Bachelor       771
High School    728
Diploma        468
Masters        210
Other          137
<NA>            87
Name: count, dtype: Int64

In [ ]:
clean_df["has_mentor"] = clean_df["has_mentor"].astype("string").str.strip()

In [ ]:
mentor_mapping = {
    "1": "Yes",
    "TRUE": "Yes",
    "Yes": "Yes",
    "yes": "Yes",
    "Y": "Yes",

    "0": "No",
    "FALSE": "No",
    "No": "No",
    "no": "No",
    "N": "No"
}

clean_df["has_mentor"] = clean_df["has_mentor"].replace(mentor_mapping)

In [ ]:
print(clean_df["has_mentor"].value_counts(dropna=False))

has_mentor
No      1437
Yes      902
<NA>      62
Name: count, dtype: Int64

In [ ]:
clean_df["device"] = clean_df["device"].astype("string").str.strip()

In [ ]:
device_mapping = {
    "mobile": "Mobile",
    "Mobile": "Mobile",
    "MOBILE": "Mobile",
    "phone": "Mobile",

    "laptop": "Laptop",
    "Laptop": "Laptop",
    "notebook": "Laptop",

    "desktop": "Desktop",
    "Desktop": "Desktop",
    "PC": "Desktop",

    "tablet": "Tablet",
    "Tablet": "Tablet",
    "ipad": "Tablet"
}

clean_df["device"] = clean_df["device"].replace(device_mapping)

In [ ]:
print(clean_df["device"].value_counts(dropna=False))

device
Mobile     1252
Laptop      716
Desktop     282
Tablet      151
Name: count, dtype: Int64

In [ ]:
print(clean_df["referral_source"].value_counts(dropna=False))

referral_source
instagram         659
school_partner    533
friend            458
youtube           362
ngo_outreach      254
other             135
Name: count, dtype: int64

In [ ]:
print(clean_df["payment_plan"].value_counts(dropna=False))

payment_plan
free           1087
scholarship     789
paid            525
Name: count, dtype: int64

In [ ]:
bad_age = clean_df[(clean_df["age"] < 10) | (clean_df["age"] > 100)]

print("Number of impossible age values:", len(bad_age))
print(bad_age[["learner_id", "age"]].to_string(index=False))

Number of impossible age values: 29
learner_id   age
   L-02703 300.0
   L-02530  -3.0
   L-01185 199.0
   L-00454   0.0
   L-00870   0.0
   L-02448 300.0
   L-02461 300.0
   L-00842 300.0
   L-00919   0.0
   L-01071 199.0
   L-02523   0.0
   L-01721 300.0
   L-00616   0.0
   L-00090 300.0
   L-00503  -3.0
   L-01128 300.0
   L-01276   0.0
   L-01264  -3.0
   L-00261  -3.0
   L-01682 199.0
   L-00691 199.0
   L-01977 300.0
   L-02080  -3.0
   L-01953 199.0
   L-02321   0.0
   L-02292 199.0
   L-01445  -3.0
   L-00409 199.0
   L-01909 300.0

In [ ]:
clean_df.loc[(clean_df["age"] < 10) | (clean_df["age"] > 100), "age"] = np.nan

In [ ]:
print("Impossible ages remaining:",
      ((clean_df["age"] < 10) | (clean_df["age"] > 100)).sum())

print("Missing ages now:", clean_df["age"].isna().sum())

Impossible ages remaining: 0
Missing ages now: 178

In [ ]:
bad_hours = clean_df[clean_df["hours_per_week_pledged"] > 168]

print("Number of impossible pledged-hours values:", len(bad_hours))
print(bad_hours[["learner_id", "hours_per_week_pledged"]].to_string(index=False))

Number of impossible pledged-hours values: 8
learner_id  hours_per_week_pledged
   L-01420                   318.3
   L-02033                   319.0
   L-02360                   233.8
   L-00722                   325.3
   L-00249                   300.9
   L-02268                   326.8
   L-02345                   220.3
   L-01157                   272.8

In [ ]:
clean_df.loc[clean_df["hours_per_week_pledged"] > 168, "hours_per_week_pledged"] = np.nan

In [ ]:
print(
    "Impossible pledged-hours remaining:",
    (clean_df["hours_per_week_pledged"] > 168).sum()
)

print(
    "Missing pledged-hours now:",
    clean_df["hours_per_week_pledged"].isna().sum()
)

Impossible pledged-hours remaining: 0
Missing pledged-hours now: 114

In [ ]:
bad_video = clean_df[clean_df["video_watch_pct"] > 100]

print("Number of video watch values above 100:", len(bad_video))
print(
    bad_video[["learner_id", "video_watch_pct"]].to_string(index=False)
)

Number of video watch values above 100: 36
learner_id  video_watch_pct
   L-02774            101.0
   L-01194            102.6
   L-01358            112.9
   L-00025            104.2
   L-00162            105.9
   L-01947            107.9
   L-01573            103.2
   L-01230            113.1
   L-00480            107.6
   L-02712            110.1
   L-02431            109.7
   L-00567            105.7
   L-02036            101.9
   L-00053            115.2
   L-00701            102.0
   L-01753            112.8
   L-00017            115.3
   L-00968            103.7
   L-02104            103.6
   L-01377            101.9
   L-00663            101.5
   L-01544            114.5
   L-02268            112.1
   L-02518            105.3
   L-02295            102.0
   L-00924            114.8
   L-00657            112.2
   L-02044            111.1
   L-01242            106.7
   L-00233            104.6
   L-01354            114.9
   L-01259            100.8
   L-01222            111.2
   L-01127            115.2
   L-01165            103.6
   L-01337            102.2

In [ ]:
clean_df.loc[clean_df["video_watch_pct"] > 100, "video_watch_pct"] = 100

In [ ]:
print(
    "Video watch values above 100 remaining:",
    (clean_df["video_watch_pct"] > 100).sum()
)

print(
    "Maximum video watch percentage:",
    clean_df["video_watch_pct"].max()
)

Video watch values above 100 remaining: 0
Maximum video watch percentage: 100.0

In [ ]:
bad_logins = clean_df[
    (clean_df["weekly_logins_avg"] < 0) |
    (clean_df["weekly_logins_avg"] > 7)
]

print("Number of impossible weekly login values:", len(bad_logins))

print(
    bad_logins[
        ["learner_id", "weekly_logins_avg"]
    ].to_string(index=False)
)

Number of impossible weekly login values: 0
Empty DataFrame
Columns: [learner_id, weekly_logins_avg]
Index: []

In [ ]:
bad_assignments = clean_df[
    (clean_df["assignments_submitted"] < 0) |
    (clean_df["assignments_submitted"] > 10)
]

print("Number of impossible assignment values:", len(bad_assignments))

print(
    bad_assignments[
        ["learner_id", "assignments_submitted"]
    ].to_string(index=False)
)

Number of impossible assignment values: 0
Empty DataFrame
Columns: [learner_id, assignments_submitted]
Index: []

In [ ]:
print(clean_df["forum_posts"].describe())

count    2401.000000
mean        3.257393
std         2.517351
min         0.000000
25%         1.000000
50%         3.000000
75%         5.000000
max        14.000000
Name: forum_posts, dtype: float64

In [ ]:
bad_last_login = clean_df[
    (clean_df["days_since_last_login"] < 0) |
    (clean_df["days_since_last_login"] > 21)
]

print("Number of impossible last-login values:", len(bad_last_login))

print(
    bad_last_login[
        ["learner_id", "days_since_last_login"]
    ].to_string(index=False)
)

Number of impossible last-login values: 951
learner_id  days_since_last_login
   L-00695                     33
   L-00530                     23
   L-02228                     33
   L-02644                     25
   L-02550                     24
   L-01648                     25
   L-00847                     32
   L-01515                     27
   L-00021                     41
   L-01677                     24
   L-00871                     36
   L-00460                     33
   L-02584                     26
   L-01949                     30
   L-01912                     25
   L-02703                     27
   L-01587                     36
   L-01809                     23
   L-00387                     36
   L-02376                     30
   L-00590                     22
   L-02046                     25
   L-01420                     44
   L-00319                     23
   L-00788                     41
   L-02243                     40
   L-01812                     25
   L-02281                     24
   L-02675                     31
   L-01789                     26
   L-02766                     37
   L-00122                     59
   L-01345                     22
   L-01764                     22
   L-01038                     24
   L-02084                     22
   L-01183                     28
   L-00138                     28
   L-00315                     32
   L-01629                     23
   L-00855                     44
   L-01389                     34
   L-02729                     32
   L-02517                     45
   L-02041                     24
   L-01291                     29
   L-02286                     42
   L-01543                     32
   L-00803                     23
   L-02259                     31
   L-02746                     22
   L-01029                     25
   L-01570                     32
   L-01290                     45
   L-02050                     32
   L-01707                     38
   L-02216                     28
   L-00681                     22
   L-00939                     41
   L-01207                     30
   L-01850                     37
   L-01357                     26
   L-00572                     25
   L-00162                     22
   L-00141                     25
   L-01466                     22
   L-01903                     32
   L-00101                     35
   L-00283                     24
   L-02200                     32
   L-00581                     37
   L-01928                     27
   L-02185                     32
   L-02033                     24
   L-01489                     36
   L-00684                     26
   L-00484                     25
   L-01640                     32
   L-02521                     24
   L-02166                     23
   L-02561                     28
   L-00992                     31
   L-00549                     26
   L-00980                     35
   L-02776                     24
   L-01637                     33
   L-00655                     44
   L-01624                     26
   L-00389                     36
   L-02525                     55
   L-02085                     31
   L-01756                     26
   L-02282                     29
   L-02555                     42
   L-01054                     36
   L-00913                     22
   L-00765                     30
   L-01630                     42
   L-01164                     30
   L-02093                     46
   L-02159                     22
   L-01244                     34
   L-02261                     24
   L-02575                     36
   L-00102                     22
   L-01896                     25
   L-00620                     23
   L-01185                     33
   L-01911                     23
   L-00647                     29
   L-00428                     26
   L-01085                     42
   L-00736                     30
   L-01181                     32
   L-02287                     39
   L-01813                     31
   L-00490                     38
   L-00336                     22
   L-02474                     23
   L-02224                     22
   L-02015                     23
   L-00568                     25
   L-01983                     33
   L-00641                     32
   L-00481                     25
   L-00762                     30
   L-01773                     33
   L-01010                     27
   L-00430                     39
   L-01572                     24
   L-02318                     40
   L-00294                     31
   L-02188                     27
   L-01191                     38
   L-02775                     33
   L-00199                     25
   L-02300                     22
   L-02360                     41
   L-00166                     32
   L-01557                     31
   L-01022                     22
   L-02386                     30
   L-00253                     23
   L-00561                     43
   L-02768                     22
   L-00534                     41
   L-01681                     36
   L-00838                     24
   L-00522                     42
   L-01658                     23
   L-01672                     35
   L-01053                     25
   L-02562                     39
   L-00255                     32
   L-01311                     37
   L-00483                     31
   L-01955                     39
   L-00967                     31
   L-02102                     24
   L-01774                     31
   L-00399                     36
   L-01047                     40
   L-01765                     32
   L-02269                     39
   L-01802                     35
   L-01094                     31
   L-02350                     55
   L-01455                     37
   L-01795                     30
   L-00130                     42
   L-00330                     24
   L-01215                     34
   L-00083                     31
   L-00670                     34
   L-02650                     27
   L-00284                     26
   L-02194                     25
   L-01176                     38
   L-00653                     31
   L-02145                     37
   L-01324                     28
   L-01611                     34
   L-00213                     22
   L-02366                     37
   L-00542                     25
   L-00832                     23
   L-00285                     23
   L-00960                     23
   L-01143                     30
   L-00809                     23
   L-02448                     44
   L-01662                     42
   L-00709                     30
   L-01406                     42
   L-02750                     30
   L-00282                     39
   L-01579                     37
   L-01781                     32
   L-00776                     27
   L-01871                     32
   L-02047                     33
   L-02676                     27
   L-00065                     37
   L-00092                     28
   L-01905                     23
   L-00312                     40
   L-01258                     38
   L-01365                     32
   L-00154                     39
   L-02532                     31
   L-00767                     31
   L-02372                     50
   L-00936                     30
   L-02429                     32
   L-02731                     41
   L-00963                     31
   L-02450                     24
   L-01830                     27
   L-02762                     27
   L-01654                     31
   L-00720                     31
   L-02279                     30
   L-00397                     42
   L-01915                     38
   L-02572                     22
   L-02712                     23
   L-02391                     23
   L-01708                     38
   L-00856                     31
   L-01879                     59
   L-01817                     30
   L-02409                     34
   L-02645                     24
   L-01495                     32
   L-00531                     22
   L-02699                     25
   L-01012                     32
   L-00544                     26
   L-00890                     32
   L-01533                     25
   L-00618                     34
   L-00326                     35
   L-02111                     23
   L-00711                     39
   L-02406                     38
   L-02398                     39
   L-00842                     44
   L-01690                     25
   L-02152                     29
   L-01783                     30
   L-01288                     25
   L-00237                     27
   L-01295                     26
   L-00299                     28
   L-00082                     25
   L-01696                     40
   L-00250                     28
   L-02760                     31
   L-02027                     30
   L-02382                     33
   L-02413                     38
   L-01160                     24
   L-01736                     27
   L-00052                     30
   L-02357                     28
   L-02431                     36
   L-02616                     22
   L-00573                     41
   L-02609                     22
   L-00725                     36
   L-02054                     30
   L-01743                     23
   L-00344                     31
   L-00554                     46
   L-00447                     49
   L-01822                     23
   L-01326                     29
   L-01972                     30
   L-01071                     38
   L-00792                     26
   L-00207                     23
   L-00457                     40
   L-01643                     22
   L-00519                     29
   L-00977                     28
   L-02316                     42
   L-01257                     25
   L-00479                     27
   L-01201                     22
   L-02648                     34
   L-02763                     23
   L-01825                     26
   L-00161                     22
   L-02576                     31
   L-02596                     32
   L-00235                     23
   L-00248                     35
   L-00422                     35
   L-00553                     22
   L-01360                     31
   L-02773                     24
   L-00528                     51
   L-01331                     28
   L-01986                     31
   L-01999                     26
   L-01613                     22
   L-00703                     24
   L-00985                     30
   L-00606                     30
   L-00652                     41
   L-00805                     35
   L-00435                     23
   L-02358                     39
   L-00431                     26
   L-00704                     23
   L-02523                     26
   L-00252                     26
   L-00320                     28
   L-02291                     22
   L-00244                     26
   L-00727                     33
   L-01313                     26
   L-02061                     30
   L-02542                     43
   L-01721                     25
   L-00843                     23
   L-01597                     22
   L-00386                     24
   L-00323                     22
   L-02757                     36
   L-00147                     32
   L-01978                     40
   L-00020                     43
   L-02283                     28
   L-01254                     36
   L-02770                     26
   L-02336                     29
   L-00204                     29
   L-00986                     36
   L-00749                     44
   L-02207                     35
   L-00443                     22
   L-01411                     37
   L-02503                     45
   L-01243                     23
   L-00797                     30
   L-02083                     26
   L-02637                     26
   L-01112                     26
   L-01555                     42
   L-01210                     43
   L-00259                     34
   L-02310                     30
   L-00852                     23
   L-02242                     26
   L-02317                     23
   L-01006                     27
   L-00759                     37
   L-02058                     29
   L-01276                     23
   L-01492                     38
   L-00417                     40
   L-01363                     57
   L-00569                     27
   L-00008                     25
   L-01862                     45
   L-00742                     22
   L-00231                     31
   L-00292                     24
   L-00599                     25
   L-00060                     34
   L-00881                     28
   L-02449                     26
   L-01769                     27
   L-00961                     42
   L-00642                     42
   L-02453                     24
   L-02066                     23
   L-00576                     32
   L-01424                     22
   L-01751                     31
   L-00886                     32
   L-00053                     28
   L-01256                     28
   L-02559                     24
   L-01060                     23
   L-01425                     46
   L-01876                     26
   L-00883                     25
   L-02496                     33
   L-01753                     24
   L-02334                     37
   L-00857                     25
   L-01653                     36
   L-01997                     26
   L-01262                     23
   L-00959                     23
   L-00690                     28
   L-01942                     25
   L-00096                     27
   L-02067                     30
   L-01107                     33
   L-01058                     24
   L-02125                     30
   L-02755                     26
   L-01193                     22
   L-00516                     22
   L-01453                     33
   L-00697                     36
   L-00782                     34
   L-01301                     29
   L-01282                     57
   L-01754                     35
   L-00019                     26
   L-00396                     24
   L-01264                     40
   L-02198                     27
   L-01815                     49
   L-02759                     32
   L-01117                     35
   L-01388                     32
   L-01956                     27
   L-02625                     29
   L-02706                     22
   L-02218                     24
   L-02439                     43
   L-01745                     24
   L-00745                     44
   L-02128                     29
   L-00827                     32
   L-02029                     45
   L-00278                     30
   L-00137                     39
   L-02387                     29
   L-01698                     36
   L-01617                     43
   L-02221                     24
   L-00181                     24
   L-01124                     35
   L-02579                     26
   L-00958                     38
   L-01465                     25
   L-00823                     34
   L-00459                     34
   L-01428                     31
   L-00501                     40
   L-01440                     46
   L-02179                     35
   L-01737                     32
   L-01482                     42
   L-01108                     28
   L-00676                     29
   L-00193                     27
   L-01393                     50
   L-02074                     35
   L-01975                     52
   L-01600                     28
   L-02199                     27
   L-02158                     29
   L-00089                     30
   L-02716                     41
   L-00023                     22
   L-02548                     36
   L-02078                     44
   L-00990                     27
   L-02657                     32
   L-02624                     24
   L-01752                     44
   L-01129                     38
   L-00440                     24
   L-01734                     27
   L-02118                     24
   L-01368                     37
   L-00875                     53
   L-01068                     27
   L-02628                     24
   L-01444                     41
   L-02184                     26
   L-01355                     22
   L-02785                     31
   L-01697                     26
   L-01938                     29
   L-02527                     44
   L-01002                     34
   L-00826                     24
   L-01057                     35
   L-02643                     44
   L-00744                     38
   L-01689                     56
   L-01216                     24
   L-00295                     29
   L-00075                     35
   L-02075                     27
   L-00106                     42
   L-02059                     25
   L-02684                     22
   L-00794                     41
   L-02470                     32
   L-01890                     30
   L-00691                     29
   L-01967                     29
   L-00571                     33
   L-01686                     24
   L-01742                     42
   L-02094                     23
   L-00172                     22
   L-00656                     27
   L-02447                     26
   L-01075                     24
   L-00192                     23
   L-01568                     29
   L-02515                     35
   L-02106                     23
   L-01132                     32
   L-00087                     34
   L-01977                     28
   L-00047                     29
   L-00716                     23
   L-01272                     33
   L-01621                     43
   L-00196                     25
   L-00757                     31
   L-00895                     23
   L-01377                     26
   L-02560                     25
   L-00070                     47
   L-01922                     33
   L-02700                     28
   L-02608                     30
   L-01502                     22
   L-00793                     34
   L-01823                     25
   L-00777                     23
   L-01426                     25
   L-01998                     28
   L-01486                     39
   L-00663                     33
   L-01990                     22
   L-02214                     28
   L-01446                     23
   L-02615                     27
   L-00635                     25
   L-02605                     23
   L-00197                     51
   L-01943                     31
   L-01004                     24
   L-00763                     26
   L-02008                     41
   L-01397                     22
   L-00916                     30
   L-02753                     25
   L-01623                     27
   L-00159                     26
   L-00580                     29
   L-02330                     29
   L-02595                     24
   L-02541                     23
   L-02367                     57
   L-00448                     45
   L-00876                     25
   L-02268                     32
   L-02396                     26
   L-01079                     34
   L-01963                     36
   L-01037                     35
   L-02231                     24
   L-00654                     34
   L-01872                     49
   L-02182                     26
   L-02626                     43
   L-00710                     23
   L-02132                     43
   L-00427                     29
   L-02635                     30
   L-02606                     37
   L-01691                     28
   L-02260                     24
   L-02080                     31
   L-01937                     35
   L-02613                     32
   L-02091                     37
   L-02513                     26
   L-01106                     33
   L-00232                     43
   L-01728                     38

In [ ]:
print(clean_df["days_since_last_login"].describe())

count    2401.000000
mean       19.224906
std        11.826851
min         0.000000
25%        10.000000
50%        18.000000
75%        27.000000
max        70.000000
Name: days_since_last_login, dtype: float64

In [ ]:
print(clean_df.isnull().sum())

learner_id                   0
signup_date                  0
age                        178
city_tier                   49
education                   87
hours_per_week_pledged     114
weekly_logins_avg           89
assignments_submitted        0
forum_posts                  0
video_watch_pct            143
has_mentor                  62
device                       0
referral_source              0
payment_plan                 0
days_since_last_login        0
certificate_issued           0
final_score               1270
notes                     1204
completed_course             9
dtype: int64

In [ ]:
clean_df["age"] = clean_df["age"].fillna(clean_df["age"].median())

In [ ]:
print(clean_df["age"].isnull().sum())

0

In [ ]:
clean_df["hours_per_week_pledged"] = clean_df["hours_per_week_pledged"].fillna(
    clean_df["hours_per_week_pledged"].median()
)

In [ ]:
print(clean_df["hours_per_week_pledged"].isnull().sum())

0

In [ ]:
clean_df["weekly_logins_avg"] = clean_df["weekly_logins_avg"].fillna(
    clean_df["weekly_logins_avg"].median()
)

In [ ]:
print(clean_df["weekly_logins_avg"].isnull().sum())

0

In [ ]:
clean_df["video_watch_pct"] = clean_df["video_watch_pct"].fillna(
    clean_df["video_watch_pct"].median()
)

In [ ]:
print(clean_df["video_watch_pct"].isnull().sum())

0

In [ ]:
clean_df["city_tier"] = clean_df["city_tier"].fillna("Unknown")

In [ ]:
print(clean_df["city_tier"].isnull().sum())

0

In [ ]:
print(clean_df["certificate_issued"].value_counts(dropna=False))

certificate_issued
no       304
No       304
0        300
FALSE    296
N        294
Y        193
TRUE     188
yes      182
Yes      175
1        165
Name: count, dtype: int64

In [ ]:
clean_df["certificate_issued"] = clean_df["certificate_issued"].astype("string").str.strip().str.lower()

In [ ]:
print(clean_df["certificate_issued"].value_counts(dropna=False))

certificate_issued
no       608
yes      357
0        300
false    296
n        294
y        193
true     188
1        165
Name: count, dtype: Int64

In [ ]:
clean_df["certificate_issued"] = clean_df["certificate_issued"].replace({
    "no": "no",
    "0": "no",
    "false": "no",
    "n": "no",
    "yes": "yes",
    "1": "yes",
    "true": "yes",
    "y": "yes"
})

In [ ]:
print(clean_df["certificate_issued"].value_counts(dropna=False))

certificate_issued
no     1498
yes     903
Name: count, dtype: Int64

In [ ]:
print(clean_df["final_score"].describe())

count    1131.000000
mean       70.323696
std        16.777700
min        13.300000
25%        62.100000
50%        74.200000
75%        81.950000
max       100.000000
Name: final_score, dtype: float64

In [ ]:
print("Number of impossible final scores:", ((clean_df["final_score"] < 0) | (clean_df["final_score"] > 100)).sum())

Number of impossible final scores: 0

In [ ]:
print(clean_df.groupby("completed_course")["final_score"].agg(["count", "mean", "min", "max"]))

                  count       mean   min    max
completed_course
0.0                 237  43.347257  13.3   62.0
1.0                 891  77.523793  48.8  100.0

In [ ]:
print("Final score is related to course completion")
print("We will check this column later because it may cause data leakage")

Final score is related to course completion
We will check this column later because it may cause data leakage

In [ ]:
print(clean_df["notes"].value_counts(dropna=False).head(20))

notes
NaN                        1204
asked about certificate     224
follow up next intake       204
duplicate?  check           200
-                           196
requested extension         188
called on phone             185
Name: count, dtype: int64

In [ ]:
clean_df["notes"] = clean_df["notes"].replace("-", pd.NA)

In [ ]:
print(clean_df["notes"].value_counts(dropna=False))

notes
NaN                        1204
asked about certificate     224
follow up next intake       204
duplicate?  check           200
<NA>                        196
requested extension         188
called on phone             185
Name: count, dtype: int64

In [ ]:
print(clean_df.isnull().sum())

learner_id                   0
signup_date                  0
age                          0
city_tier                    0
education                   87
hours_per_week_pledged       0
weekly_logins_avg            0
assignments_submitted        0
forum_posts                  0
video_watch_pct              0
has_mentor                  62
device                       0
referral_source              0
payment_plan                 0
days_since_last_login        0
certificate_issued           0
final_score               1270
notes                     1400
completed_course             9
dtype: int64

In [ ]:
print(clean_df["education"].value_counts(dropna=False))

education
Bachelor       771
High School    728
Diploma        468
Masters        210
Other          137
<NA>            87
Name: count, dtype: Int64

In [ ]:
clean_df["education"] = clean_df["education"].fillna("Bachelor")

In [ ]:
print(clean_df["education"].isnull().sum())

0

In [ ]:
print(clean_df["has_mentor"].value_counts(dropna=False))

has_mentor
No      1437
Yes      902
<NA>      62
Name: count, dtype: Int64

In [ ]:
clean_df["has_mentor"] = clean_df["has_mentor"].fillna("No")

In [ ]:
print(clean_df["has_mentor"].isnull().sum())

0

In [ ]:
print(clean_df["final_score"].isnull().sum())

1270

In [ ]:
print(pd.crosstab(clean_df["final_score"].isna(), clean_df["completed_course"], dropna=False))

completed_course   0.0  1.0  NaN
final_score
False              237  891    3
True              1264    0    6

In [ ]:
print(pd.crosstab(clean_df["certificate_issued"], clean_df["final_score"].isna()))

final_score         False  True
certificate_issued
no                    246   1252
yes                   885     18

In [ ]:
print(clean_df["completed_course"].isnull().sum())

9

In [ ]:
clean_df = clean_df.dropna(subset=["completed_course"])

In [ ]:
print(clean_df["completed_course"].isnull().sum())

0

In [ ]:
print(clean_df.isnull().sum())

learner_id                   0
signup_date                  0
age                          0
city_tier                    0
education                    0
hours_per_week_pledged       0
weekly_logins_avg            0
assignments_submitted        0
forum_posts                  0
video_watch_pct              0
has_mentor                   0
device                       0
referral_source              0
payment_plan                 0
days_since_last_login        0
certificate_issued           0
final_score               1264
notes                     1396
completed_course             0
dtype: int64

In [ ]:
print("Final cleaned data shape:", clean_df.shape)

Final cleaned data shape: (2392, 19)

In [ ]:
print("Number of duplicate rows:", clean_df.duplicated().sum())

Number of duplicate rows: 0

In [ ]:
print(clean_df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 2392 entries, 0 to 2483
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   learner_id              2392 non-null   object
 1   signup_date             2392 non-null   object
 2   age                     2392 non-null   float64
 3   city_tier               2392 non-null   string
 4   education               2392 non-null   string
 5   hours_per_week_pledged  2392 non-null   float64
 6   weekly_logins_avg       2392 non-null   float64
 7   assignments_submitted   2392 non-null   int64
 8   forum_posts             2392 non-null   int64
 9   video_watch_pct         2392 non-null   float64
 10  has_mentor              2392 non-null   string
 11  device                  2392 non-null   string
 12  referral_source         2392 non-null   object
 13  payment_plan            2392 non-null   object
 14  days_since_last_login   2392 non-null   int64
 15  certificate_issued      2392 non-null   string
 16  final_score             1128 non-null   float64
 17  notes                   996 non-null    object
 18  completed_course        2392 non-null   float64
dtypes: float64(6), int64(3), object(5), string(5)
memory usage: 373.8+ KB
None

In [ ]:
clean_df = clean_df.reset_index(drop=True)

In [ ]:
print(clean_df.shape)

(2392, 19)

Day 4-Preparing Data for machine laerning

In [ ]:
print(clean_df["completed_course"].value_counts())

completed_course
0.0    1501
1.0     891
Name: count, dtype: int64

In [ ]:
print(clean_df["completed_course"].value_counts(normalize=True) * 100)

completed_course
0.0    62.750836
1.0    37.249164
Name: proportion, dtype: float64

In [ ]:
print(clean_df.columns.tolist())

['learner_id', 'signup_date', 'age', 'city_tier', 'education', 'hours_per_week_pledged', 'weekly_logins_avg', 'assignments_submitted', 'forum_posts', 'video_watch_pct', 'has_mentor', 'device', 'referral_source', 'payment_plan', 'days_since_last_login', 'certificate_issued', 'final_score', 'notes', 'completed_course']

In [ ]:
X = clean_df.drop(columns=["completed_course", "learner_id", "final_score", "certificate_issued", "notes"])

In [ ]:
y = clean_df["completed_course"]

In [ ]:
print(X.shape)

(2392, 14)

In [ ]:
print(y.shape)

(2392,)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [ ]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(1913, 14)
(479, 14)
(1913,)
(479,)

In [ ]:
print(X.isnull().sum())

signup_date               0
age                       0
city_tier                 0
education                 0
hours_per_week_pledged    0
weekly_logins_avg         0
assignments_submitted     0
forum_posts               0
video_watch_pct           0
has_mentor                0
device                    0
referral_source           0
payment_plan              0
days_since_last_login     0
dtype: int64

In [ ]:
print(X.dtypes)

signup_date                       object
age                              float64
city_tier                 string[python]
education                 string[python]
hours_per_week_pledged           float64
weekly_logins_avg                float64
assignments_submitted              int64
forum_posts                        int64
video_watch_pct                  float64
has_mentor                string[python]
device                    string[python]
referral_source                   object
payment_plan                      object
days_since_last_login              int64
dtype: object

In [ ]:
print(X["signup_date"].head())

0    2026-01-22
1    2026-06-02
2    20-05-2026
3    2026-01-19
4    16/02/2026
Name: signup_date, dtype: object

In [ ]:
X["signup_date"] = pd.to_datetime(X["signup_date"], dayfirst=True, format="mixed")

In [ ]:
print(X["signup_date"].dtype)

datetime64[ns]

In [ ]:
X["signup_month"] = X["signup_date"].dt.month

In [ ]:
X["signup_dayofweek"] = X["signup_date"].dt.dayofweek

In [ ]:
X = X.drop(columns=["signup_date"])

In [ ]:
print(X.shape)

(2392, 15)

In [ ]:
print(X.select_dtypes(include=["object", "string"]).columns)

Index(['city_tier', 'education', 'has_mentor', 'device', 'referral_source',
       'payment_plan'],
      dtype='object')

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False)

In [ ]:
categorical_cols = ["city_tier", "education", "has_mentor", "device", "referral_source", "payment_plan"]

In [ ]:
X_encoded = encoder.fit_transform(X[categorical_cols])

In [ ]:
print(X_encoded.shape)

(2392, 24)

In [ ]:
numeric_cols = X.drop(columns=categorical_cols)

In [ ]:
X_final = pd.concat(
    [numeric_cols.reset_index(drop=True),
     pd.DataFrame(X_encoded)],
    axis=1
)
X_final.columns = X_final.columns.astype(str)

In [ ]:
print(X_final.shape)

(2392, 33)

In [ ]:
print(y.shape)

(2392,)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X_final, y, test_size=0.2, random_state=42, stratify=y
)

In [ ]:
print(X_train.shape)
print(X_test.shape)

(1913, 33)
(479, 33)

In [ ]:
from sklearn.dummy import DummyClassifier

In [ ]:
baseline = DummyClassifier(strategy="most_frequent")

In [ ]:
X_final.columns = X_final.columns.astype(str)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X_final, y, test_size=0.2, random_state=42, stratify=y
)

In [ ]:
baseline.fit(X_train, y_train)

DummyClassifier(strategy='most_frequent')

In [ ]:
baseline_pred = baseline.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
baseline_accuracy = accuracy_score(y_test, baseline_pred)

In [ ]:
print(baseline_accuracy)

0.6283924843423799

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model = LogisticRegression(max_iter=1000)

In [ ]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [ ]:
model_pred = model.predict(X_test)

In [ ]:
model_accuracy = accuracy_score(y_test, model_pred)

In [ ]:
print(model_accuracy)

0.7724425887265136

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
print(classification_report(y_test, model_pred))

              precision    recall  f1-score   support

         0.0       0.80      0.86      0.83       301
         1.0       0.72      0.63      0.67       178

    accuracy                           0.77       479
   macro avg       0.76      0.74      0.75       479
weighted avg       0.77      0.77      0.77       479

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
cm = confusion_matrix(y_test, model_pred)

In [ ]:
print(cm)

[[258  43]
 [ 66 112]]

In [ ]:
print("Baseline Accuracy:", baseline_accuracy)
print("Logistic Regression Accuracy:", model_accuracy)

Baseline Accuracy: 0.6283924843423799
Logistic Regression Accuracy: 0.7724425887265136

Day 5-Model Comparison and Improvement

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
dt_model = DecisionTreeClassifier(random_state=42)

In [ ]:
dt_model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [ ]:
dt_pred = dt_model.predict(X_test)

In [ ]:
dt_accuracy = accuracy_score(y_test, dt_pred)

In [ ]:
print("Decision Tree Accuracy:", dt_accuracy)

Decision Tree Accuracy: 0.7118997912317327

In [ ]:
print(classification_report(y_test, dt_pred))

              precision    recall  f1-score   support

         0.0       0.79      0.74      0.76       301
         1.0       0.60      0.66      0.63       178

    accuracy                           0.71       479
   macro avg       0.69      0.70      0.70       479
weighted avg       0.72      0.71      0.71       479

In [ ]:
confusion_matrix(y_test, dt_pred)

array([[224,  77],
       [ 61, 117]])

In [ ]:
dt_train_accuracy = dt_model.score(X_train, y_train)

In [ ]:
print("Decision Tree Training Accuracy:", dt_train_accuracy)

Decision Tree Training Accuracy: 1.0

In [ ]:
dt_model2 = DecisionTreeClassifier(max_depth=5, random_state=42)

In [ ]:
dt_model2.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=5, random_state=42)

In [ ]:
dt_pred2 = dt_model2.predict(X_test)

In [ ]:
dt_accuracy2 = accuracy_score(y_test, dt_pred2)

In [ ]:
print("Decision Tree (Depth=5) Accuracy:", dt_accuracy2)

Decision Tree (Depth=5) Accuracy: 0.7640918580375783

In [ ]:
dt_train_accuracy2 = dt_model2.score(X_train, y_train)

In [ ]:
print("Decision Tree (Depth=5) Training Accuracy:", dt_train_accuracy2)

Decision Tree (Depth=5) Training Accuracy: 0.7746994249869316

In [ ]:
print(classification_report(y_test, dt_pred2))

              precision    recall  f1-score   support

         0.0       0.81      0.81      0.81       301
         1.0       0.68      0.69      0.68       178

    accuracy                           0.76       479
   macro avg       0.75      0.75      0.75       479
weighted avg       0.76      0.76      0.76       479

In [ ]:
confusion_matrix(y_test, dt_pred2)

array([[244,  57],
       [ 56, 122]])

In [ ]:
print("Baseline Accuracy:", baseline_accuracy)
print("Logistic Regression Accuracy:", model_accuracy)
print("Decision Tree Accuracy:", dt_accuracy)
print("Decision Tree (Depth=5) Accuracy:", dt_accuracy2)

Baseline Accuracy: 0.6283924843423799
Logistic Regression Accuracy: 0.7724425887265136
Decision Tree Accuracy: 0.7118997912317327
Decision Tree (Depth=5) Accuracy: 0.7640918580375783

Day 6-Final Model Selection & Evaluation

---

In [ ]:
final_pred = model.predict(X_test)

In [ ]:
final_accuracy = accuracy_score(y_test, final_pred)

In [ ]:
print("Final Model Accuracy:", final_accuracy)

Final Model Accuracy: 0.7724425887265136

In [ ]:
print(classification_report(y_test, final_pred))

              precision    recall  f1-score   support

         0.0       0.80      0.86      0.83       301
         1.0       0.72      0.63      0.67       178

    accuracy                           0.77       479
   macro avg       0.76      0.74      0.75       479
weighted avg       0.77      0.77      0.77       479

In [ ]:
confusion_matrix(y_test, final_pred)

array([[258,  43],
       [ 66, 112]])

In [ ]:
from sklearn.metrics import precision_score

In [ ]:
final_precision = precision_score(y_test, final_pred)

In [ ]:
from sklearn.metrics import recall_score

In [ ]:
final_recall = recall_score(y_test, final_pred)

In [ ]:
from sklearn.metrics import f1_score

In [ ]:
final_f1 = f1_score(y_test, final_pred)

In [ ]:
print("Final Precision:", final_precision)
print("Final Recall:", final_recall)
print("Final F1-Score:", final_f1)

Final Precision: 0.7225806451612903
Final Recall: 0.6292134831460674
Final F1-Score: 0.6726726726726727

In [ ]:
print("Baseline:", baseline_accuracy)
print("Logistic Regression:", model_accuracy)
print("Decision Tree:", dt_accuracy)
print("Decision Tree (Depth=5):", dt_accuracy2)

Baseline: 0.6283924843423799
Logistic Regression: 0.7724425887265136
Decision Tree: 0.7118997912317327
Decision Tree (Depth=5): 0.7640918580375783

In [ ]:
improvement = final_accuracy - baseline_accuracy

In [ ]:
print("Improvement over Baseline:", improvement)

Improvement over Baseline: 0.14405010438413368

In [ ]:
import joblib

In [ ]:
joblib.dump(model, "final_logistic_regression_model.pkl")

['final_logistic_regression_model.pkl']

In [ ]:
loaded_model = joblib.load("final_logistic_regression_model.pkl")

In [ ]:
loaded_pred = loaded_model.predict(X_test)

In [ ]:
loaded_accuracy = accuracy_score(y_test, loaded_pred)

In [ ]:
print("Loaded Model Accuracy:", loaded_accuracy)

Loaded Model Accuracy: 0.7724425887265136

In [ ]:
print("Original Accuracy:", final_accuracy)
print("Loaded Model Accuracy:", loaded_accuracy)

Original Accuracy: 0.7724425887265136
Loaded Model Accuracy: 0.7724425887265136

In [ ]:
print("Final Model: Logistic Regression")

Final Model: Logistic Regression

Day 7-Final Course Completion Review

In [ ]:
print("Final Model: Logistic Regression")
print("Final Accuracy:", final_accuracy)

Final Model: Logistic Regression
Final Accuracy: 0.7724425887265136

In [ ]:
print("Baseline Accuracy:", baseline_accuracy)
print("Logistic Regression Accuracy:", model_accuracy)
print("Decision Tree Accuracy:", dt_accuracy)
print("Decision Tree (Depth=5) Accuracy:", dt_accuracy2)

Baseline Accuracy: 0.6283924843423799
Logistic Regression Accuracy: 0.7724425887265136
Decision Tree Accuracy: 0.7118997912317327
Decision Tree (Depth=5) Accuracy: 0.7640918580375783

In [ ]:
print("Final Accuracy:", round(final_accuracy * 100, 2), "%")

Final Accuracy: 77.24 %

In [ ]:
print("Improvement over Baseline:", round(improvement * 100, 2), "%")

Improvement over Baseline: 14.41 %

In [ ]:
print(classification_report(y_test, final_pred))

              precision    recall  f1-score   support

         0.0       0.80      0.86      0.83       301
         1.0       0.72      0.63      0.67       178

    accuracy                           0.77       479
   macro avg       0.76      0.74      0.75       479
weighted avg       0.77      0.77      0.77       479

In [ ]:
print(confusion_matrix(y_test, final_pred))

[[258  43]
 [ 66 112]]

In [ ]:
print("Final Precision:", final_precision)
print("Final Recall:", final_recall)
print("Final F1-Score:", final_f1)

Final Precision: 0.7225806451612903
Final Recall: 0.6292134831460674
Final F1-Score: 0.6726726726726727